### ISSUE TITLE
[US] As a user, I want to receive an email in order to confirm my account

### ISSUE THREAD

**Issue by samuelbelolo** [Terraform-GUI/terraform-gui#19]
## Tasks:
- [ ] send a confirmation email post registration
- [ ] add a token field in the User document
- [ ] disallow login if user hasn't confirm his email
- [ ] add controller route in order to validate user account
