### ISSUE TITLE
[US] As a user, I want to be able to CRUD my projects in the client

### ISSUE THREAD

**Issue by PIERRONMarc** [Terraform-GUI/terraform-gui#26]
## Tasks:
- [x] display a list of projects
- [x] open an existing project
- [x] delete a project
- [x] create a new project
- [x] rename project
- [x] save current project
