### ISSUE TITLE
[US] As a user, I want to fill AWS nodes data by clicking on the node

### ISSUE THREAD

**Issue by PIERRONMarc** [Terraform-GUI/terraform-gui#35]
## Tasks:
- [x] create a popup on node click
- [x] in the popup, generate a form based on backend node data
- [x] prefill form with backend data if node already exists (by opening a project for example)
