### ISSUE TITLE
[US] As a developer, I want to sync some web client data with my backend

### ISSUE THREAD

**Issue by PIERRONMarc** [Terraform-GUI/terraform-gui#49]
## Tasks:
- [x] load aws resources
- [x] load users projects
- [x] create a new project
- [x] update an existing project
- [x] delete a project
