### ISSUE TITLE
[US] As a user, I want to update and delete my profile

### ISSUE THREAD

**Issue by lucaslehot** [Terraform-GUI/terraform-gui#5]
## Tasks:
- [x] Creation of update endpoint
- [x] Creation of update method in userController
- [x] Creation od delete endpoint
- [x] Creation of delete method in userController
